#!/bin/sh

srcdir=`dirname "$0"`

if [ -f ./run-prelude ]; then . ./run-prelude; fi

if [ -z "$CONFIG" ]; then
    CONFIG="testing"
fi

if [ ! -f ${srcdir}/configs/${CONFIG}.rkt ]; then
    echo "Config ${CONFIG} not found: configs/${CONFIG}.rkt not readable"
    exit 1
fi

PLTSTDERR="
	info
	warning@GC
	warning@cm
	warning@compiler/cm
	warning@module-prefetch
	warning@setup/parallel-build
	warning@cm-accomplice
	warning@online-check-syntax
	error@racket/contract
	error@collapsible-cache-fail
	error@collapsible-contract-arrow-wrapper-arity
	error@collapsible-contract-bailout
	error@collapsible-merging
	error@collapsible-value-bailout
        "
export PLTSTDERR
echo '============================================='
exec ${RACKET}racket ${srcdir}/configs/${CONFIG}.rkt 2>&1
