#!/bin/sh

if [ -f ./run-prelude ]; then . ./run-prelude; fi

if [ -z "$CONFIG" ]; then
    CONFIG=$(hostname -s)
    echo 'Environment variable CONFIG not defined; defaulting to "'"${CONFIG}"'"'
fi

if [ ! -f configs/${CONFIG}.rkt ]; then
    echo "Config ${CONFIG} not found: configs/${CONFIG}.rkt not readable"
    exit 1
fi

PLTSTDERR=info warning@cm warning@compiler/cm warning@module-prefetch warning@setup/parallel-build warning@cm-accomplice warning@online-check-syntax error@racket/contract
export PLTSTDERR
echo '============================================='
cd src
exec ${RACKET}racket ../configs/${CONFIG}.rkt 2>&1
